# M40006 In-Course Assessment

# Specimen Paper

## Two Hours

### Answer all questions, submitting your answers as a single Jupyter notebook.

## Question 1 (20 marks)

Using Python, and showing your code, calculate:

(a) $5^{2+8}$ as an int.

In [1]:
print(5 ** (2 + 8))

9765625


(b) $\displaystyle{\sin\left(\frac{\pi}{12}\right)}$ as a float.

In [2]:
import math

print(math.sin(math.pi/12))

0.25881904510252074


(c) The residue of $19207812^{41506412}$ modulo $32271881$ as an int.

In [3]:
print(pow(19207812, 41506412, 32271881))

8333554


(d) As floats, the two roots of $12\,x^2 + 11\,x - 15 = 0$ (you may use the quadratic formula).

In [4]:
print((-11 + math.sqrt((11) ** 2 - 4 * 12 * -15)) / (2 * 12))

print((-11 - math.sqrt((11) ** 2 - 4 * 12 * -15)) / (2 * 12))

0.75
-1.6666666666666667


(e) As complexes, the two roots of $9\,z^2 - 12\,z + 5 = 0$ (you may use the quadratic formula).

In [5]:
import cmath

print((12 + cmath.sqrt((12) ** 2 - 4 * 9 * 5)) / (2 * 9))

print((12 - cmath.sqrt((12) ** 2 - 4 * 9 * 5)) / (2 * 9))

(0.6666666666666666+0.3333333333333333j)
(0.6666666666666666-0.3333333333333333j)


(f) As a complex, the value of $\ln (-e)$.

In [6]:
print(cmath.log(-math.e))

(1+3.141592653589793j)


## Question 2 (20 marks)

(a) Assigning in each case an appropriate variable name, create:

(i) A <code>range</code> object containing the numbers $5, 9, 13, \dots, 101, 105$.

In [54]:
range(5,106,4)



range(5, 106, 4)

(ii) A list containing the numbers $5, 9, 13, \dots, 101, 105$.

In [49]:
list_range1 = [n for n in range(5,106,4)]

print(list_range1)

[5, 9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65, 69, 73, 77, 81, 85, 89, 93, 97, 101, 105]


(iii) A tuple containing the numbers $5, 9, 13, \dots, 101, 105$.

In [12]:
tuple_range1 = tuple(list_range1)

print(tuple_range1)

(5, 9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65, 69, 73, 77, 81, 85, 89, 93, 97, 101, 105)


(b) By slicing your <code>range</code> object from part (a)(i), create a <code>range</code> object containing its fifth, sixth, seventh and eighth elements.

In [53]:
range1[5:9]

range(25, 41, 4)

(c) Append the number $109$ to your list from part (a)(ii).

In [50]:
list_range1.append(109)

print(list_range1)

[5, 9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65, 69, 73, 77, 81, 85, 89, 93, 97, 101, 105, 109]


(d) Create a tuple consisting of your tuple from part (a)(iii), repeated five times.

In [23]:
tuple2 = 5 * tuple_range1

print(tuple2)

(5, 9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65, 69, 73, 77, 81, 85, 89, 93, 97, 101, 105, 5, 9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65, 69, 73, 77, 81, 85, 89, 93, 97, 101, 105, 5, 9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65, 69, 73, 77, 81, 85, 89, 93, 97, 101, 105, 5, 9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65, 69, 73, 77, 81, 85, 89, 93, 97, 101, 105, 5, 9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65, 69, 73, 77, 81, 85, 89, 93, 97, 101, 105)


## Question 3 (30 marks)

Kepler's equation links two quantities useful in astronomy: a planet's <b>mean anomaly</b>, $M$, and its <b>eccentric anomaly</b>, $E$. Kepler's equation is
$$M = E - e\, \sin E,$$
where (lower-case) $e$ is the planet's orbital <b>eccentricity</b>.

(a) For a planet with orbital eccentricity $e=0.5$, find the mean anomaly if the eccentric anomaly is $E = 0.6$ radians.

In [25]:
print(0.6 - 0.5 * math.sin(0.6))

0.3176787633024823


(b) For a planet with orbital eccentricity $e=0.5$, find the eccentric anomaly if the mean anomaly is $M = \pi/2$ radians. Do this by using a <code>for</code> loop to iterate
$$E_{n+1} = M + e\,\sin E_n$$
ten times, with $E_0 = M = \pi/2$. Print your answer at the end.

In [26]:
E = math.pi / 2
M = math.pi / 2
e = 0.5

for n in range(1, 11):
    E = M + e * math.sin(E)

print(E)

2.020979881456128


(c) For a planet with orbital eccentricity $e=0.5$, find the eccentric anomaly if the mean anomaly is $M = \pi/2$ radians. Do this by using a <code>while</code> loop to iterate
$$E_{n+1} = M + e\,\sin E_n$$
until successive iterates lie within $5.0 \times 10^{-7}$ of one another. Print your answer at the end.

In [31]:
E = math.pi / 2
M = math.pi / 2
e = 0.5
iterc = 0

while abs(E - (M + e * math.sin(E))) > 5e-7:
    E = M + e * math.sin(E)
    iterc = iterc + 1

print(E)
print(iterc)

2.020980198395953
9


(d) For a planet with orbital eccentricity $e=0.5$, find the eccentric anomaly if the mean anomaly is $M = \pi/2$ radians. Do this by using a <code>while</code> loop to iterate
$$E_{n+1} = E_n - \frac{E_n - e\,\sin E_n - M}{1 - e\,\cos E_n}$$
until successive iterates lie within $5.0 \times 10^{-7}$ of one another. Print your answer at the end.

In [32]:
E = math.pi / 2
M = math.pi / 2
e = 0.5
iterd = 0

while abs(E - (E - (E - e * math.sin(E) - M) / (1 - e * math.cos(E)))) > 5e-7:
    E = E - (E - e * math.sin(E) - M) / (1 - e * math.cos(E))
    iterd = iterd + 1

print(E)
print(iterd)

2.020979974372671
3


(e) By counting the number of iterations necessary in each case, compare the speeds of convergence of the methods you used in parts (c) and (d).

In [34]:
print('d is much faster as it only takes 3 iterations opposed to the 9 of c')

d is much faster as it only takes 3 iterations opposed to the 9 of c


## Question 4 (30 marks)

(a) Write a Python function called <code>eccentric_anomaly</code>, which 
<ul>
    <li>takes as its arguments a value for the mean anomaly, $M$, the eccentricity, $e$ and a <code>tolerance</code>, and</li>
    <li>returns an estimate for the eccentric anomaly.
</ul>

This estimate should based on iterating one or other of the two iterations in Question 4 parts (c) and (d) (you may choose which) until successive iterates lie within <code>tolerance</code> of one another.

In [38]:
def eccentric_anomaly(M, e, tolerance):
    E = math.pi / 2
    while abs(E - (E - (E - e * math.sin(E) - M) / (1 - e * math.cos(E)))) > tolerance:
        E = E - (E - e * math.sin(E) - M) / (1 - e * math.cos(E))
    return E

(b) Test your function on the case $e=0.5$, $M=\pi/2$, using a tolerance of $5.0\times 10^{-7}$. Test it, too, on the edge cases $M=\pi, e=0.5$ and $M=\pi/2, e=0.0,$ for which the mean anomaly and the eccentric anomaly ought to be equal. Comment <b>briefly</b> on the results of your tests.

In [40]:
print(eccentric_anomaly(math.pi / 2, 0.5, 5e-7))
print(eccentric_anomaly(math.pi, 0.5, 5e-7))
print(eccentric_anomaly(math.pi / 2, 0.0, 5e-7))
print('As you can see my function is valid as it works on a general case and edge cases')

2.020979974372671
3.1415929664547164
1.5707963267948966
As you can see my function is valid as it works on a general case and edge cases


(c) Using in each case an eccentricity of $e=0.5$ and a tolerance of $5.0 \times 10^{-7}$, calculate the eccentric anomaly for values of the mean anomaly between $0$ and $2\pi$ radians in steps of $\pi/12$. For full marks, do this using a single-line <b>comprehension</b>.

In [45]:
list_eccentric_anomaly = [eccentric_anomaly(M * math.pi / 12, 0.5, 5e-7) for M in range(0, 25)]

print(list_eccentric_anomaly)

[1.3156251262025354e-15, 0.5026929141712205, 0.9220066053188057, 1.261703062121573, 1.5470566699470845, 1.7963339489319325, 2.020979974372671, 2.228343136932135, 2.4234054584754343, 2.6097539544001584, 2.790130045031977, 2.9667635514343496, 3.1415929664547164, 3.3164219982464136, 3.493055586056898, 3.6734312890794953, 3.8597798487042008, 4.0548425148313605, 4.262205368954982, 4.486851357105382, 4.736128638036367, 5.021482250276675, 5.361178701853829, 5.7804923937411985, 6.283185307179587]
